version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "postcss-preset-env"
        versions: ["6.x"]
    assignees:
      - "FlorentinTh"
