version: '3'

services:
  le2ml-gui:
    image: 'le2ml-gui:latest'
    restart: always
    ports:
      - 8082:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    network_mode: bridge
